apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-microservice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sairam19062006/gitops-microservice-pipeline.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
